### ISSUE TITLE
How to determine render has finished?

### ISSUE THREAD

**Issue by larjohn** [okgreece/sealer#5]
@akariv, How can we be sure that rendering a visualization in the OS Viewer embed page has finished? 

Currently, sealer tests for the existence of an SVG element, which is not correct, of course. Can we check for the existence of a different element and be sure that it works universally?

**Comment by akariv** [comment]
https://github.com/openspending/openspending/issues/1088

When the window bound variable containing the data appears, you should also be able to see the visualisation.
